version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - test-cache-{{ .Branch }}-
            - test-cache-
      - run:
          name: install
          command: 'yarn install --production=false'
      - run:
          name: test
          command: 'yarn run circleci'
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
      - run:
          name: coverage
          command: 'yarn run coverage'
      - save_cache:
          key: test-cache-{{ .Branch }}
          paths:
            - '.test-cache'
