name: Test
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: npm install

      - name: Install codecov
        run: npm install -g codecov

      - name: Test
        run: npm run ci

      - name: Test build
        run: npm run build
